"""Provider-neutral records and ports for reference retrieval."""

from .corpus import (
    ChunkingConfiguration,
    CorpusRejected,
    CorpusSource,
    ExtractorConfiguration,
    LoadedReferenceCorpus,
    ReferenceCorpusManifest,
    chunking_fingerprint_for,
    corpus_fingerprint_for,
    extractor_fingerprint_for,
    load_reference_corpus,
)
from .index import (
    BM25Configuration,
    IndexRejected,
    InMemoryBM25Index,
    RetrievalReport,
    RetrievalReportMatch,
    SparseIndexManifest,
    bm25_configuration_fingerprint,
    sparse_index_fingerprint,
)
from .ports import (
    LogicalIndexStrategy,
    ProviderEvidenceLevel,
    RetrievalAdapterDescriptor,
    RetrievalIndexPort,
    retrieval_adapter_fingerprint,
)
from .records import (
    CitationRecord,
    ReferenceAsset,
    ReferenceChunk,
    ReferenceDocument,
    ScoredChunk,
    TextSourceSpan,
    asset_id_for,
    chunk_id_for,
    citation_from_scored_chunk,
    document_id_for,
)
from .service import (
    LexicalReferenceService,
    ReferenceRetrievalService,
    RetrievalAdapterRejected,
)

__all__ = [
    "BM25Configuration",
    "CitationRecord",
    "ChunkingConfiguration",
    "CorpusRejected",
    "CorpusSource",
    "ExtractorConfiguration",
    "IndexRejected",
    "InMemoryBM25Index",
    "LexicalReferenceService",
    "LogicalIndexStrategy",
    "LoadedReferenceCorpus",
    "ProviderEvidenceLevel",
    "ReferenceAsset",
    "ReferenceChunk",
    "ReferenceCorpusManifest",
    "ReferenceDocument",
    "ReferenceRetrievalService",
    "RetrievalAdapterDescriptor",
    "RetrievalAdapterRejected",
    "RetrievalIndexPort",
    "RetrievalReport",
    "RetrievalReportMatch",
    "ScoredChunk",
    "SparseIndexManifest",
    "TextSourceSpan",
    "asset_id_for",
    "bm25_configuration_fingerprint",
    "chunking_fingerprint_for",
    "chunk_id_for",
    "citation_from_scored_chunk",
    "corpus_fingerprint_for",
    "document_id_for",
    "extractor_fingerprint_for",
    "load_reference_corpus",
    "retrieval_adapter_fingerprint",
    "sparse_index_fingerprint",
]
